CREATE TABLE books (
    id VARCHAR NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
